"         _
"  _   __(_)___ ___  __________
" | | / / / __ `__ \/ ___/ ___/
" | |/ / / / / / / / /  / /__
" |___/_/_/ /_/ /_/_/   \___/

" General Setup -

filetype plugin indent on

set noswapfile
set showcmd
set ruler
" set backspace=2

set ignorecase
set wildmenu wildmode=list,full
set autochdir
set path+=**

set cursorline
set number relativenumber
set mouse=a

set wrap
set linebreak
set textwidth=80

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set breakindent

set splitright
set splitbelow
set confirm

" Appearance -

syntax on
colorscheme jellybeans
if $TERM == 'linux'
    colorscheme murphy
endif

" Vim Plugins -

call plug#begin('~/.vim/plugged')
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'jiangmiao/auto-pairs'
Plug 'vimwiki/vimwiki'
Plug 'kezhenxu94/vim-mysql-plugin'
call plug#end()

" Configs -

let g:netrw_bufsettings = 'number nowrap'
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<C-h>"
let g:vimwiki_table_mappings = 0
let g:tex_flavor="latex"

" Mappings -

let mapleader = "\<Space>"

" Normal Mode Mappings:
nnoremap <M-k> :normal! km5jdd`5P<CR>
nnoremap <M-j> :normal! ddp<CR>
nnoremap <M-S-k> :normal! yyP<CR>
nnoremap <M-S-j> :normal! yyp<CR>
nnoremap <leader><Space> :normal! magqip`a<CR>
nnoremap <F9> :call CodeRunner()<CR>
" Switch Splits
nnoremap <leader>h <C-w>h
nnoremap <leader>j <C-w>j
nnoremap <leader>k <C-w>k
nnoremap <leader>l <C-w>l
" Switching and Deleting Buffers
nnoremap <leader>s :buffers<CR>:buffer<Space>
nnoremap <leader>d :buffers<CR>:bdelete<Space>

" Insert Mode Mappings:
inoremap <C-a> <C-o>:normal! ^<CR>
inoremap <C-e> <C-o>:normal! $<CR>
inoremap <C-u> <C-o>:normal! d^<CR>
inoremap <C-k> <C-o>:normal! d$<CR>
" Autocompletion
inoremap <expr> j pumvisible()?"<C-n>":"j"
inoremap <expr> k pumvisible()?"<C-p>":"k"
inoremap <expr> q pumvisible()?"<C-e>":"q"

" Command Mode Mappings:
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

" Auto Commands -

augroup RunOnEvent
    autocmd!
    autocmd Filetype * set formatoptions=tqcnj1]p
    autocmd BufWritePre * %s/\s\+$//e " strip trailing spaces
augroup END

if has("autocmd")
    " Automatically jump to the last cursor position on entering vim
    autocmd BufReadPost * if line("'\"") > 0 && line ("'\"") <= line("$")
                \ | execute "normal g'\"zz" | endif
endif

" User-defined Commands

command! Vimconfig execute("tabnew ~/.vim/vimrc")
command! Wordbook execute("tabnew ~/notes/Archives/.lexicon.md")
command! Bookmarks execute("tabnew ~/notes/Archives/.bookmarks.md")
command! Ftconfig execute("tabnew ~/.vim/after/ftplugin")

" Abbreviations -

abbr ture true
abbr fasle false
abbr adn and
abbr teh the
abbr fmri fMRI
" Inserting Dates:
iab <expr> today strftime("%a %b %d %Y")
iab tomorrow <C-r>=system('date -d tomorrow +\%a\ \%b\ \%d\ \%Y')<CR><BS>
