#! /usr/bin/env python
# This script is a part of a bash script
# Print the tab position of the localFilename open in the current firefox
# session; if localFilename is not open print 0.

import listurl
import sys

def hasLocalURL(url_list):

    ''' The hasLocalURL() function creates a list of local URLs and checks if
    the given local URL is in the list. '''

    local_url_list = [ url for url in url_list
            if url.startswith(localURLOutset) ]

    return localURL in local_url_list

# Global Var Declarations

localFilename = sys.argv[1]
localURLOutset = "file://"

localURL = localURLOutset + localFilename

if (hasLocalURL(listurl.url_list)):
    localURLIndex = listurl.url_list.index(localURL)
    localURLTabPosition = localURLIndex + 1
else:
    localURLTabPosition = 0

print(localURLTabPosition)
