#! /bin/bash

function declareAppropriateVars() {
    case $1 in

        # Selecting programming languages:
        -c) programmingLanguage=c ;;
        -cpp) programmingLanguage=cpp ;;
        -py) programmingLanguage=python ;;
        -j) programmingLanguage=java ;;
        -sh) programmingLanguage=bash ;;

        # Selecting programming pardigms:
        -oop) programmingParadigm=OOP ;;

        # Selecting Projects:

        *) echo "'$(echo $1 | cut -c 2-)' is not an option"
            exit 111
            ;;
    esac
}

if [ $# -gt 2 ] ; then
    echo "bash: $(basename $0): too many arguments"
    exit 111
else
    while [ -n "$1" ] ; do
        declareAppropriateVars $1
        shift
    done
fi

if [ -z ${programmingLanguage} ] ; then
    vim /home/nikin/Coding/

elif [[ -n ${programmingParadigm} ]] ; then
    vim /home/nikin/Coding/${programmingLanguage}/${programmingParadigm}/

else
    vim /home/nikin/Coding/${programmingLanguage}/
fi
