#! /bin/bash

scrot --select --line style=dash --freeze \
"$HOME/Pictures/screenshots/.temporary.png"

if [ -f $HOME/Pictures/screenshots/.temporary.png ] ; then

    fileName=$(zenity --title Snip\ Tool --file-selection \
        --filename=$HOME/notes/ --save --confirm-overwrite )
    mv $HOME/Pictures/screenshots/.temporary.png "$fileName"

fi

rm -rf $HOME/Pictures/screenshots/.temporary.png
