#! /bin/bash

# scrot /home/nikin/Pictures/Screenshot.png
# convert /home/nikin/Pictures/Screenshot.png -blur 0x5 /home/nikin/Pictures/Screenshot_blurred.png
# convert /home/nikin/Pictures/Screenshot_blurred.png /home/nikin/Pictures/logos/starbucks_gnu.png \
#     -gravity center -composite -matte /home/nikin/Pictures/screenlock.png
# i3lock -i /home/nikin/Pictures/screenlock.png --no-unlock-indicator
# rm -f /home/nikin/Pictures/Screenshot*.png

i3lock -i /home/nikin/Pictures/screenlock.png --no-unlock-indicator
