#! /bin/bash

battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)

while (true)
do
    # if [ ${battery_capacity} -lt 30 ] ; then
        zenity --width=150 --info --text="$battery_capacity %" &
    # fi
done

